name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]        

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials to start an EC2
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: me-south-1
      - name: Start EC2 instance
        run: |
          aws ec2 start-instances --instance-ids i-0d1bb221ce6aaca52
          aws ec2 wait instance-running --instance-ids i-0d1bb221ce6aaca52
          sleep 60
      
      - name: Copy monitoring files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "monitoring"
          target: "/home/ec2-user/CLOUD-OBSERVABILITY-PLATFORM"

      
      - name: Copy app to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app"
          target: "/home/ec2-user/CLOUD-OBSERVABILITY-PLATFORM"

      
      - name: Restart Docker Compose on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/CLOUD-OBSERVABILITY-PLATFORM/monitoring
            sudo docker-compose down || true
            sudo docker-compose up -d --build

      - name: Restart Docker Compose on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/CLOUD-OBSERVABILITY-PLATFORM/monitoring
            echo "Stopping all containers..."
            sudo docker-compose down || true
            echo "Removing any old app container..."
            sudo docker rm -f myapp || true
            echo "Starting fresh build..."
            sudo docker-compose up -d --build


